/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ExtendedNote {
  'title' : string,
  'selfDestructAt' : [] | [bigint],
  'content' : string,
  'imagePath' : [] | [ExternalBlob],
  'createdAt' : bigint,
  'lastModified' : bigint,
}
export interface ExtendedNoteInput {
  'title' : string,
  'selfDestructAt' : [] | [bigint],
  'content' : string,
  'imagePath' : [] | [ExternalBlob],
}
export type ExternalBlob = Uint8Array;
export interface Note {
  'title' : string,
  'selfDestructAt' : [] | [bigint],
  'content' : string,
  'createdAt' : bigint,
  'lastModified' : bigint,
}
export interface PersistentRecoveryData {
  'creationTime' : Time,
  'mnemonic' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'muteGreeting' : boolean,
  'isFirstTimeUser' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cleanupExpiredShareLinks' : ActorMethod<[], undefined>,
  'clearPersistentRecoveryData' : ActorMethod<[], undefined>,
  'createExtendedNote' : ActorMethod<[ExtendedNoteInput], undefined>,
  'createNote' : ActorMethod<[string, string, [] | [bigint]], undefined>,
  'createShareLink' : ActorMethod<
    [Uint8Array, Uint8Array, [] | [bigint], boolean],
    string
  >,
  'deleteAllExpiredExtendedNotes' : ActorMethod<[], undefined>,
  'deleteExtendedNote' : ActorMethod<[string], undefined>,
  'deleteNote' : ActorMethod<[string], undefined>,
  'extendedNoteCleanup' : ActorMethod<[], undefined>,
  'getAllExtendedNotes' : ActorMethod<[], Array<ExtendedNote>>,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExtendedNote' : ActorMethod<[string], ExtendedNote>,
  'getMuteGreetingPreference' : ActorMethod<[], boolean>,
  'getNote' : ActorMethod<[string], Note>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listPersistentRecoveryData' : ActorMethod<
    [],
    Array<[Principal, PersistentRecoveryData]>
  >,
  'markWelcomePopupSeen' : ActorMethod<[], undefined>,
  'migrate' : ActorMethod<[], undefined>,
  'openShareLink' : ActorMethod<[string], [Uint8Array, Uint8Array]>,
  'retrievePersistentRecoveryPhrase' : ActorMethod<[], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchExtendedNotes' : ActorMethod<[string], Array<ExtendedNote>>,
  'searchNotes' : ActorMethod<[string], Array<Note>>,
  'setExtendedNoteSelfDestructTimer' : ActorMethod<[string, bigint], undefined>,
  'setMuteGreetingPreference' : ActorMethod<[boolean], undefined>,
  'setSelfDestructTimer' : ActorMethod<[string, bigint], undefined>,
  'storePersistentRecoveryData' : ActorMethod<[string], undefined>,
  'updateExtendedNote' : ActorMethod<
    [string, string, [] | [bigint], [] | [ExternalBlob]],
    undefined
  >,
  'updateNote' : ActorMethod<[string, string, [] | [bigint]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];