/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ExtendedNoteInput = IDL.Record({
  'title' : IDL.Text,
  'selfDestructAt' : IDL.Opt(IDL.Int),
  'content' : IDL.Text,
  'imagePath' : IDL.Opt(ExternalBlob),
});
export const ExtendedNote = IDL.Record({
  'title' : IDL.Text,
  'selfDestructAt' : IDL.Opt(IDL.Int),
  'content' : IDL.Text,
  'imagePath' : IDL.Opt(ExternalBlob),
  'createdAt' : IDL.Int,
  'lastModified' : IDL.Int,
});
export const Note = IDL.Record({
  'title' : IDL.Text,
  'selfDestructAt' : IDL.Opt(IDL.Int),
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'lastModified' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'muteGreeting' : IDL.Bool,
  'isFirstTimeUser' : IDL.Bool,
});
export const Time = IDL.Int;
export const PersistentRecoveryData = IDL.Record({
  'creationTime' : Time,
  'mnemonic' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cleanupExpiredShareLinks' : IDL.Func([], [], []),
  'clearPersistentRecoveryData' : IDL.Func([], [], []),
  'createExtendedNote' : IDL.Func([ExtendedNoteInput], [], []),
  'createNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Int)], [], []),
  'createShareLink' : IDL.Func(
      [IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8), IDL.Opt(IDL.Int), IDL.Bool],
      [IDL.Text],
      [],
    ),
  'deleteAllExpiredExtendedNotes' : IDL.Func([], [], []),
  'deleteExtendedNote' : IDL.Func([IDL.Text], [], []),
  'deleteNote' : IDL.Func([IDL.Text], [], []),
  'extendedNoteCleanup' : IDL.Func([], [], []),
  'getAllExtendedNotes' : IDL.Func([], [IDL.Vec(ExtendedNote)], ['query']),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExtendedNote' : IDL.Func([IDL.Text], [ExtendedNote], ['query']),
  'getMuteGreetingPreference' : IDL.Func([], [IDL.Bool], ['query']),
  'getNote' : IDL.Func([IDL.Text], [Note], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listPersistentRecoveryData' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, PersistentRecoveryData))],
      ['query'],
    ),
  'markWelcomePopupSeen' : IDL.Func([], [], []),
  'migrate' : IDL.Func([], [], []),
  'openShareLink' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8)],
      [],
    ),
  'retrievePersistentRecoveryPhrase' : IDL.Func([], [IDL.Text], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchExtendedNotes' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ExtendedNote)],
      ['query'],
    ),
  'searchNotes' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
  'setExtendedNoteSelfDestructTimer' : IDL.Func([IDL.Text, IDL.Int], [], []),
  'setMuteGreetingPreference' : IDL.Func([IDL.Bool], [], []),
  'setSelfDestructTimer' : IDL.Func([IDL.Text, IDL.Int], [], []),
  'storePersistentRecoveryData' : IDL.Func([IDL.Text], [], []),
  'updateExtendedNote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Int), IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'updateNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Int)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ExtendedNoteInput = IDL.Record({
    'title' : IDL.Text,
    'selfDestructAt' : IDL.Opt(IDL.Int),
    'content' : IDL.Text,
    'imagePath' : IDL.Opt(ExternalBlob),
  });
  const ExtendedNote = IDL.Record({
    'title' : IDL.Text,
    'selfDestructAt' : IDL.Opt(IDL.Int),
    'content' : IDL.Text,
    'imagePath' : IDL.Opt(ExternalBlob),
    'createdAt' : IDL.Int,
    'lastModified' : IDL.Int,
  });
  const Note = IDL.Record({
    'title' : IDL.Text,
    'selfDestructAt' : IDL.Opt(IDL.Int),
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'lastModified' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'muteGreeting' : IDL.Bool,
    'isFirstTimeUser' : IDL.Bool,
  });
  const Time = IDL.Int;
  const PersistentRecoveryData = IDL.Record({
    'creationTime' : Time,
    'mnemonic' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cleanupExpiredShareLinks' : IDL.Func([], [], []),
    'clearPersistentRecoveryData' : IDL.Func([], [], []),
    'createExtendedNote' : IDL.Func([ExtendedNoteInput], [], []),
    'createNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Int)], [], []),
    'createShareLink' : IDL.Func(
        [IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8), IDL.Opt(IDL.Int), IDL.Bool],
        [IDL.Text],
        [],
      ),
    'deleteAllExpiredExtendedNotes' : IDL.Func([], [], []),
    'deleteExtendedNote' : IDL.Func([IDL.Text], [], []),
    'deleteNote' : IDL.Func([IDL.Text], [], []),
    'extendedNoteCleanup' : IDL.Func([], [], []),
    'getAllExtendedNotes' : IDL.Func([], [IDL.Vec(ExtendedNote)], ['query']),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExtendedNote' : IDL.Func([IDL.Text], [ExtendedNote], ['query']),
    'getMuteGreetingPreference' : IDL.Func([], [IDL.Bool], ['query']),
    'getNote' : IDL.Func([IDL.Text], [Note], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listPersistentRecoveryData' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, PersistentRecoveryData))],
        ['query'],
      ),
    'markWelcomePopupSeen' : IDL.Func([], [], []),
    'migrate' : IDL.Func([], [], []),
    'openShareLink' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8)],
        [],
      ),
    'retrievePersistentRecoveryPhrase' : IDL.Func([], [IDL.Text], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchExtendedNotes' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ExtendedNote)],
        ['query'],
      ),
    'searchNotes' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
    'setExtendedNoteSelfDestructTimer' : IDL.Func([IDL.Text, IDL.Int], [], []),
    'setMuteGreetingPreference' : IDL.Func([IDL.Bool], [], []),
    'setSelfDestructTimer' : IDL.Func([IDL.Text, IDL.Int], [], []),
    'storePersistentRecoveryData' : IDL.Func([IDL.Text], [], []),
    'updateExtendedNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Int), IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'updateNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Int)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };